modified

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -157,263 +157,263 @@ jobs:
             npm audit fix 
 
 
-  deploy-infrastructure:
-    docker:
-      - image: cimg/base:stable
-    steps:
-      - checkout
-      - install_awscli
-      - run:
-          name: Ensure back-end infrastructure exists
-          command: |
-            aws cloudformation deploy \
-              --template-file .circleci/files/backend.yml \
-              --tags project=udapeople \
-              --stack-name udapeople-backend-${CIRCLE_WORKFLOW_ID} \
-              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID}" 
+#   deploy-infrastructure:
+#     docker:
+#       - image: cimg/base:stable
+#     steps:
+#       - checkout
+#       - install_awscli
+#       - run:
+#           name: Ensure back-end infrastructure exists
+#           command: |
+#             aws cloudformation deploy \
+#               --template-file .circleci/files/backend.yml \
+#               --tags project=udapeople \
+#               --stack-name udapeople-backend-${CIRCLE_WORKFLOW_ID} \
+#               --parameter-overrides ID="${CIRCLE_WORKFLOW_ID}" 
 
-      - run:
-          name: Ensure front-end infrastructure exist
-          command: |
-            aws cloudformation deploy \
-              --template-file .circleci/files/frontend.yml \
-              --tags project=udapeople \
-              --stack-name udapeople-frontend-${CIRCLE_WORKFLOW_ID} \
-              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID}" 
+#       - run:
+#           name: Ensure front-end infrastructure exist
+#           command: |
+#             aws cloudformation deploy \
+#               --template-file .circleci/files/frontend.yml \
+#               --tags project=udapeople \
+#               --stack-name udapeople-frontend-${CIRCLE_WORKFLOW_ID} \
+#               --parameter-overrides ID="${CIRCLE_WORKFLOW_ID}" 
 
-      - run:
-          name: Add back-end ip to ansible inventory
-          command: |
-            BACKEND_PUBLIC_IP=$(aws ec2 describe-instances \
-              --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID}" \
-              --query 'Reservations[*].Instances[*].PublicIpAddress' \
-              --output text)
-            echo $BACKEND_PUBLIC_IP >> .circleci/ansible/inventory.txt
-            cat .circleci/ansible/inventory.txt
+#       - run:
+#           name: Add back-end ip to ansible inventory
+#           command: |
+#             BACKEND_PUBLIC_IP=$(aws ec2 describe-instances \
+#               --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID}" \
+#               --query 'Reservations[*].Instances[*].PublicIpAddress' \
+#               --output text)
+#             echo $BACKEND_PUBLIC_IP >> .circleci/ansible/inventory.txt
+#             cat .circleci/ansible/inventory.txt
 
-      - persist_to_workspace:
-          root: ~/
-          paths:
-            - project/.circleci/ansible/inventory.txt
+#       - persist_to_workspace:
+#           root: ~/
+#           paths:
+#             - project/.circleci/ansible/inventory.txt
 
-      - destroy-environment   
+#       - destroy-environment   
 
-  configure-infrastructure:
-    docker:
-      - image: cimg/base:stable
-    steps:
-      - checkout
-      - install_awscli
-      - install_ansible
-      - add_ssh_keys: 
-          fingerprints: ["7b:b1:28:f9:3a:94:7a:ce:6e:dc:9d:de:45:53:c6:60"]
-      - attach_workspace:
-          at: ~/
-      - run:
-          name: Configure server
-          command: |
-            cd .circleci/ansible
-            cat inventory.txt
-            ansible-playbook -i inventory.txt configure-server.yml 
-      - destroy-environment
+#   configure-infrastructure:
+#     docker:
+#       - image: cimg/base:stable
+#     steps:
+#       - checkout
+#       - install_awscli
+#       - install_ansible
+#       - add_ssh_keys: 
+#           fingerprints: ["7b:b1:28:f9:3a:94:7a:ce:6e:dc:9d:de:45:53:c6:60"]
+#       - attach_workspace:
+#           at: ~/
+#       - run:
+#           name: Configure server
+#           command: |
+#             cd .circleci/ansible
+#             cat inventory.txt
+#             ansible-playbook -i inventory.txt configure-server.yml 
+#       - destroy-environment
 
-  run-migrations:
-    docker:
-      - image: cimg/node:13.8.0
-    steps:
-      - checkout
-      - install_awscli
-      - run:
-          name: Run migrations
-          command: |
-            cd backend
-            npm install
-            # Run and save the migration output
-            npm run migrations > migrations_dump.txt
-      - run:
-          name: Send migration results to kvdb.io
-          command: |
-            if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
-            then
-              # sudo apt-get update && sudo apt-get install -y ca-certificates
-              curl https://kvdb.io/4kYQRpbTNaCfMmhFwnfVin/migration_${CIRCLE_WORKFLOW_ID}  -d '1'
-            fi 
-      - destroy-environment
-      - revert-migrations
+#   run-migrations:
+#     docker:
+#       - image: cimg/node:13.8.0
+#     steps:
+#       - checkout
+#       - install_awscli
+#       - run:
+#           name: Run migrations
+#           command: |
+#             cd backend
+#             npm install
+#             # Run and save the migration output
+#             npm run migrations > migrations_dump.txt
+#       - run:
+#           name: Send migration results to kvdb.io
+#           command: |
+#             if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
+#             then
+#               # sudo apt-get update && sudo apt-get install -y ca-certificates
+#               curl https://kvdb.io/4kYQRpbTNaCfMmhFwnfVin/migration_${CIRCLE_WORKFLOW_ID}  -d '1'
+#             fi 
+#       - destroy-environment
+#       - revert-migrations
 
-  deploy-frontend:  
-    docker:
-      - image: cimg/base:stable
-    steps:
-      - checkout
-      - install_awscli
-      - install_nodejs
-      - restore_cache:
-          keys: [frontend-build]     
-      - run:
-          name: Install dependencies
-          command: |
-            cd frontend
-            npm install
-      - run:
-          name: Get backend url
-          command: |
-            BACKEND_PUBLIC_IP=$(aws ec2 describe-instances \
-              --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID}" \
-              --query 'Reservations[*].Instances[*].PublicIpAddress' \
-              --output text)
+#   deploy-frontend:  
+#     docker:
+#       - image: cimg/base:stable
+#     steps:
+#       - checkout
+#       - install_awscli
+#       - install_nodejs
+#       - restore_cache:
+#           keys: [frontend-build]     
+#       - run:
+#           name: Install dependencies
+#           command: |
+#             cd frontend
+#             npm install
+#       - run:
+#           name: Get backend url
+#           command: |
+#             BACKEND_PUBLIC_IP=$(aws ec2 describe-instances \
+#               --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID}" \
+#               --query 'Reservations[*].Instances[*].PublicIpAddress' \
+#               --output text)
               
-            echo "API_URL=http://${BACKEND_PUBLIC_IP}:3030" >> frontend/.env
-            cat frontend/.env
-      - run:
-          name: Deploy frontend objects
-          command: |
-            cd frontend
-            npm run build
-            aws s3 cp dist s3://udapeople-${CIRCLE_WORKFLOW_ID} --recursive
+#             echo "API_URL=http://${BACKEND_PUBLIC_IP}:3030" >> frontend/.env
+#             cat frontend/.env
+#       - run:
+#           name: Deploy frontend objects
+#           command: |
+#             cd frontend
+#             npm run build
+#             aws s3 cp dist s3://udapeople-${CIRCLE_WORKFLOW_ID} --recursive
 
-      - destroy-environment
-      - revert-migrations
+#       - destroy-environment
+#       - revert-migrations
 
-  deploy-backend:
-    docker:
-      - image: cimg/base:stable
-    steps:
-      - checkout 
-      - install_awscli
-      - install_ansible
-      - install_nodejs
-      - add_ssh_keys: 
-          fingerprints: ["7b:b1:28:f9:3a:94:7a:ce:6e:dc:9d:de:45:53:c6:60"]
-      - attach_workspace:
-          at: ~/
-      - restore_cache:
-          keys: [backend-build]
+#   deploy-backend:
+#     docker:
+#       - image: cimg/base:stable
+#     steps:
+#       - checkout 
+#       - install_awscli
+#       - install_ansible
+#       - install_nodejs
+#       - add_ssh_keys: 
+#           fingerprints: ["7b:b1:28:f9:3a:94:7a:ce:6e:dc:9d:de:45:53:c6:60"]
+#       - attach_workspace:
+#           at: ~/
+#       - restore_cache:
+#           keys: [backend-build]
 
-      - run:
-          name: Install dependencies
-          command: |
-            cd backend
-            npm install
+#       - run:
+#           name: Install dependencies
+#           command: |
+#             cd backend
+#             npm install
 
-      - run:
-          name: Package Backend
-          command: |
-            cd backend
-            npm run build
-            tar -czf artifact.tar.gz dist/* package*
+#       - run:
+#           name: Package Backend
+#           command: |
+#             cd backend
+#             npm run build
+#             tar -czf artifact.tar.gz dist/* package*
 
-            cd ..
-            cp backend/artifact.tar.gz .circleci/ansible/roles/deploy/files
+#             cd ..
+#             cp backend/artifact.tar.gz .circleci/ansible/roles/deploy/files
 
-      - run:
-          name: Deploy backend
-          command: |
-            export TYPEORM_MIGRATIONS_DIR=./migrations
-            export TYPEORM_ENTITIES=./modules/domain/**/*.entity{.ts,.js}
-            export TYPEORM_MIGRATIONS=./migrations/*.ts
+#       - run:
+#           name: Deploy backend
+#           command: |
+#             export TYPEORM_MIGRATIONS_DIR=./migrations
+#             export TYPEORM_ENTITIES=./modules/domain/**/*.entity{.ts,.js}
+#             export TYPEORM_MIGRATIONS=./migrations/*.ts
 
-            cd .circleci/ansible
-            cat inventory.txt
-            ansible-playbook -i inventory.txt deploy-backend.yml 
+#             cd .circleci/ansible
+#             cat inventory.txt
+#             ansible-playbook -i inventory.txt deploy-backend.yml 
 
-      - destroy-environment
-      - revert-migrations
+#       - destroy-environment
+#       - revert-migrations
 
-  smoke-test:
-    docker:
-      - image: cimg/base:stable
-    steps:
-      - checkout
-      - install_awscli
-      - install_nodejs
-      - run:
-          name: Backend smoke test.
-          command: |
-            BACKEND_PUBLIC_IP=$(aws ec2 describe-instances \
-              --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID}" \
-              --query 'Reservations[*].Instances[*].PublicIpAddress' \
-              --output text)
+#   smoke-test:
+#     docker:
+#       - image: cimg/base:stable
+#     steps:
+#       - checkout
+#       - install_awscli
+#       - install_nodejs
+#       - run:
+#           name: Backend smoke test.
+#           command: |
+#             BACKEND_PUBLIC_IP=$(aws ec2 describe-instances \
+#               --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID}" \
+#               --query 'Reservations[*].Instances[*].PublicIpAddress' \
+#               --output text)
 
-            export API_URL=http://${BACKEND_PUBLIC_IP}:3030
-            if curl -s $API_URL/api/status | grep "ok"
-            then
-              exit 0
-            else
-              exit 1
-            fi
-      - run:
-          name: Frontend smoke test.
-          command: |
-            FRONTEND_WEBSITE=http://udapeople-${CIRCLE_WORKFLOW_ID}.s3-website.us-east-1.amazonaws.com
-            if curl -s $FRONTEND_WEBSITE | grep "Welcome"
-            then
-              exit 0
-            else
-              exit 1
-            fi
-      - destroy-environment
-      - revert-migrations
-
-
-  cloudfront-update:
-    docker:
-      - image: cimg/base:stable
-    steps:
-      - checkout
-      - install_awscli
-      - install_nodejs
-      - run:
-          name: Save Old Workflow ID to kvdb.io
-          command: |
-            export OLD_WORKFLOW_ID=$(aws cloudformation \
-                      list-exports --query "Exports[?Name==\`WorkflowID\`].Value" \
-                      --no-paginate --output text)
-            echo "Old Wokflow ID: $OLD_WORKFLOW_ID"
-            curl https://kvdb.io/4kYQRpbTNaCfMmhFwnfVin/old_workflow_id -d "${OLD_WORKFLOW_ID}" 
-      - run:
-          name: Update cloudfront distribution
-          command: |
-            aws cloudformation deploy \
-              --template-file .circleci/files/cloudfront.yml \
-              --parameter-overrides WorkflowID="${CIRCLE_WORKFLOW_ID}" \
-              --stack-name InitialStack \
-              --tags project=udapeople
-      - destroy-environment
-      - revert-migrations
+#             export API_URL=http://${BACKEND_PUBLIC_IP}:3030
+#             if curl -s $API_URL/api/status | grep "ok"
+#             then
+#               exit 0
+#             else
+#               exit 1
+#             fi
+#       - run:
+#           name: Frontend smoke test.
+#           command: |
+#             FRONTEND_WEBSITE=http://udapeople-${CIRCLE_WORKFLOW_ID}.s3-website.us-east-1.amazonaws.com
+#             if curl -s $FRONTEND_WEBSITE | grep "Welcome"
+#             then
+#               exit 0
+#             else
+#               exit 1
+#             fi
+#       - destroy-environment
+#       - revert-migrations
 
 
-
-  cleanup:
-    docker:
-      - image: cimg/base:stable
-    steps:
-      - checkout
-      - install_awscli
-      - install_nodejs
-      - run:
-          name: Remove old stacks and files
-          command: |
-            export STACKS=($(aws cloudformation list-stacks \
-                --query "StackSummaries[*].StackName" \
-                --stack-status-filter CREATE_COMPLETE --no-paginate --output text)) 
-            echo Stack names: "${STACKS[@]}"
-
-            export OldWorkflowID=$(curl --insecure https://kvdb.io/4kYQRpbTNaCfMmhFwnfVin/old_workflow_id)
-            echo Old Workflow ID: $OldWorkflowID 
-
-            if [[ "${CIRCLE_WORKFLOW_ID}" != "${OldWorkflowID}" ]]
-            then
-              echo "----------------delete confirmed------------"
-              aws s3 rm "s3://udapeople-${OldWorkflowID}" --recursive
-              aws cloudformation delete-stack --stack-name "udapeople-backend-${OldWorkflowID}"
-              aws cloudformation delete-stack --stack-name "udapeople-frontend-${OldWorkflowID}"
-            else
-              echo "-----Cannot Cleanup ------"
-            fi
+#   cloudfront-update:
+#     docker:
+#       - image: cimg/base:stable
+#     steps:
+#       - checkout
+#       - install_awscli
+#       - install_nodejs
+#       - run:
+#           name: Save Old Workflow ID to kvdb.io
+#           command: |
+#             export OLD_WORKFLOW_ID=$(aws cloudformation \
+#                       list-exports --query "Exports[?Name==\`WorkflowID\`].Value" \
+#                       --no-paginate --output text)
+#             echo "Old Wokflow ID: $OLD_WORKFLOW_ID"
+#             curl https://kvdb.io/4kYQRpbTNaCfMmhFwnfVin/old_workflow_id -d "${OLD_WORKFLOW_ID}" 
+#       - run:
+#           name: Update cloudfront distribution
+#           command: |
+#             aws cloudformation deploy \
+#               --template-file .circleci/files/cloudfront.yml \
+#               --parameter-overrides WorkflowID="${CIRCLE_WORKFLOW_ID}" \
+#               --stack-name InitialStack \
+#               --tags project=udapeople
+#       - destroy-environment
+#       - revert-migrations
 
 
-workflows:     
+
+#   cleanup:
+#     docker:
+#       - image: cimg/base:stable
+#     steps:
+#       - checkout
+#       - install_awscli
+#       - install_nodejs
+#       - run:
+#           name: Remove old stacks and files
+#           command: |
+#             export STACKS=($(aws cloudformation list-stacks \
+#                 --query "StackSummaries[*].StackName" \
+#                 --stack-status-filter CREATE_COMPLETE --no-paginate --output text)) 
+#             echo Stack names: "${STACKS[@]}"
+
+#             export OldWorkflowID=$(curl --insecure https://kvdb.io/4kYQRpbTNaCfMmhFwnfVin/old_workflow_id)
+#             echo Old Workflow ID: $OldWorkflowID 
+
+#             if [[ "${CIRCLE_WORKFLOW_ID}" != "${OldWorkflowID}" ]]
+#             then
+#               echo "----------------delete confirmed------------"
+#               aws s3 rm "s3://udapeople-${OldWorkflowID}" --recursive
+#               aws cloudformation delete-stack --stack-name "udapeople-backend-${OldWorkflowID}"
+#               aws cloudformation delete-stack --stack-name "udapeople-frontend-${OldWorkflowID}"
+#             else
+#               echo "-----Cannot Cleanup ------"
+#             fi
+
+
+# workflows:     
   default:
     jobs:
       - build-frontend
@@ -426,22 +426,22 @@ workflows:
           requires: [build-backend]
       - scan-frontend:
           requires: [build-frontend]
-      - deploy-infrastructure:
-          requires: [test-frontend, test-backend, scan-frontend, scan-backend]
-          filters:
-            branches:
-              only: [master]
-      - configure-infrastructure:
-          requires: [deploy-infrastructure]
-      - run-migrations:
-          requires: [configure-infrastructure]
-      - deploy-frontend:
-          requires: [run-migrations]
-      - deploy-backend:
-          requires: [run-migrations]
-      - smoke-test:
-          requires: [deploy-backend, deploy-frontend]
-      - cloudfront-update:
-          requires: [smoke-test]
-      - cleanup:
-          requires: [cloudfront-update]
+      # - deploy-infrastructure:
+      #     requires: [test-frontend, test-backend, scan-frontend, scan-backend]
+      #     filters:
+      #       branches:
+      #         only: [master]
+      # - configure-infrastructure:
+      #     requires: [deploy-infrastructure]
+      # - run-migrations:
+      #     requires: [configure-infrastructure]
+      # - deploy-frontend:
+      #     requires: [run-migrations]
+      # - deploy-backend:
+      #     requires: [run-migrations]
+      # - smoke-test:
+      #     requires: [deploy-backend, deploy-frontend]
+      # - cloudfront-update:
+      #     requires: [smoke-test]
+      # - cleanup:
+      #     requires: [cloudfront-update]
